GET http://localhost:5000/api/products
Content-Type: application/json

###
POST http://localhost:5000/api/AddProducts
Content-Type: application/json

{
  "title": "Laptop",
  "price": 1200.5,
  "description": "New model",
  "categoryId": "2"
}
